const API = "https://sdk.opinly.ai/v1/content";
const SITE = "https://stiledileo.com";
const CDN = "https://cdn.opinly.ai/GmtEiXrn4pxqmHqRrvfSt";

function esc(v: unknown = "") { return String(v).replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!)); }
function imageUrl(v?: string | null) { if (!v) return ""; return /^https?:\/\//.test(v) ? v : `${CDN}/${v.replace(/^\//, "")}`; }
function apiKey() { const key = Netlify.env.get("OPINLY_API_KEY"); if (!key) throw new Error("OPINLY_API_KEY is not configured"); return key; }
async function opinly(path: string) {
  const r = await fetch(`${API}${path}`, { headers: { Authorization: `Bearer ${apiKey()}` } });
  if (r.status === 404) return null;
  if (!r.ok) throw new Error(`Opinly ${r.status}: ${await r.text()}`);
  return r.json();
}
function marks(text: string, ms: any[] = []) { return ms.reduce((s,m) => m.type === "bold" ? `<strong>${s}</strong>` : m.type === "italic" ? `<em>${s}</em>` : m.type === "code" ? `<code>${s}</code>` : m.type === "link" ? `<a href="${esc(m.attrs?.href)}" rel="${m.attrs?.target === "_blank" ? "noopener noreferrer" : ""}">${s}</a>` : s, esc(text)); }
function renderNode(n: any): string {
  if (!n) return ""; const kids = () => (n.content || []).map(renderNode).join("");
  switch(n.type) {
    case "doc": return kids(); case "text": return marks(n.text || "", n.marks); case "paragraph": return `<p>${kids()}</p>`;
    case "heading": { const l=Math.min(6,Math.max(2,Number(n.attrs?.level)||2)); return `<h${l}>${kids()}</h${l}>`; }
    case "bulletList": return `<ul>${kids()}</ul>`; case "orderedList": return `<ol>${kids()}</ol>`; case "listItem": return `<li>${kids()}</li>`;
    case "blockquote": return `<blockquote>${kids()}</blockquote>`; case "hardBreak": return "<br>"; case "horizontalRule": return "<hr>";
    case "image": { const src=imageUrl(n.attrs?.fileKey || n.attrs?.src); return src ? `<figure><img src="${esc(src)}" alt="${esc(n.attrs?.altText || n.attrs?.alt || "")}" loading="lazy">${n.attrs?.caption ? `<figcaption>${esc(n.attrs.caption)}</figcaption>`:""}</figure>`:""; }
    case "table": return `<div class="table-wrap"><table>${kids()}</table></div>`; case "tableRow": return `<tr>${kids()}</tr>`; case "tableHeader": return `<th>${kids()}</th>`; case "tableCell": return `<td>${kids()}</td>`;
    default: return kids();
  }
}
function date(v?: string) { if(!v) return ""; return new Intl.DateTimeFormat("en-CA",{year:"numeric",month:"long",day:"numeric"}).format(new Date(v)); }
function layout(title:string, description:string, canonical:string, body:string, jsonLd?:any) {
  const ld = jsonLd ? `<script type="application/ld+json">${JSON.stringify(jsonLd).replace(/</g,"\\u003c")}</script>` : "";
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="robots" content="index,follow"><link rel="canonical" href="${esc(canonical)}"><meta property="og:type" content="website"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${esc(canonical)}"><link rel="icon" href="/images/favicon.png"><link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@300;400;600&family=Montserrat:wght@300;400;500&display=swap" rel="stylesheet">${ld}<style>:root{--d:#0f0d0b;--c:#1a1714;--t:#f0ebe4;--m:#9b9185;--g:#b8965a}*{box-sizing:border-box}body{margin:0;background:var(--d);color:var(--t);font:300 15px/1.8 Montserrat,sans-serif}a{color:inherit}.nav{display:flex;justify-content:space-between;align-items:center;padding:22px max(24px,5vw);border-bottom:1px solid #2c261f}.logo{font:400 22px 'Cormorant Garamond';letter-spacing:4px;text-decoration:none}.logo span,.kicker{color:var(--g)}.navlinks{display:flex;gap:22px;font-size:11px;text-transform:uppercase;letter-spacing:2px}.hero,.wrap{max-width:1120px;margin:auto;padding:70px 24px}.hero{text-align:center}.hero h1,.post h1{font:300 clamp(42px,7vw,76px)/1.05 'Cormorant Garamond';margin:.2em 0}.hero p{color:var(--m);max-width:760px;margin:auto}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:26px}.card{border:1px solid #31291f;background:var(--c);text-decoration:none;display:block}.card img{width:100%;height:220px;object-fit:cover}.card .pad{padding:24px}.card h2{font:400 27px/1.2 'Cormorant Garamond';margin:8px 0}.meta{font-size:11px;color:var(--g);letter-spacing:1px}.desc{color:var(--m)}.post{max-width:850px}.post .lead{font-size:18px;color:#cfc6ba}.content h2,.content h3{font-family:'Cormorant Garamond';font-weight:400;line-height:1.2;margin-top:1.7em}.content h2{font-size:38px}.content h3{font-size:29px}.content img{max-width:100%;height:auto}.content blockquote{border-left:2px solid var(--g);margin:2em 0;padding-left:22px;color:#cfc6ba}.content a{color:#d4b07a}.table-wrap{overflow:auto}table{border-collapse:collapse;width:100%}td,th{border:1px solid #3b3228;padding:10px}.pager{display:flex;justify-content:center;margin-top:42px}.pager a{border:1px solid var(--g);padding:10px 18px;text-decoration:none}.error{text-align:center;padding:100px 24px}@media(max-width:850px){.grid{grid-template-columns:1fr}.navlinks{display:none}}</style></head><body><nav class="nav"><a class="logo" href="/">Stile di <span>Leo</span></a><div class="navlinks"><a href="/">Home</a><a href="/blog.html">Blog</a><a href="/#contact">Contact</a></div></nav>${body}</body></html>`;
}
function postCard(p:any){ const img=imageUrl(p.titleFile?.fileKey || p.heroImage?.fileKey); return `<a class="card" href="/blog/${encodeURIComponent(p.slug)}">${img?`<img src="${esc(img)}" alt="${esc(p.titleFile?.altText || p.title)}" loading="lazy">`:""}<div class="pad"><div class="meta">${esc(p.category?.name || "Journal")} · ${esc(date(p.firstPublishedAt))}</div><h2>${esc(p.title)}</h2><div class="desc">${esc(p.description || "")}</div></div></a>`; }
async function indexPage(url:URL){ const cursor=url.searchParams.get("cursor")||""; const q=new URLSearchParams({limit:"12",sort:"newest"}); if(cursor)q.set("cursor",cursor); const list=await opinly(`/posts?${q}`); const cards=(list?.data||[]).map(postCard).join(""); const empty=`<p class="desc">No published articles yet.</p>`; const pager=list?.has_more&&list.next_cursor?`<div class="pager"><a href="/blog?cursor=${encodeURIComponent(list.next_cursor)}">More articles →</a></div>`:""; return layout("Journal | Stile di Leo","Guides on Venetian plaster, Marmorino, fireplace transformations, microcement and architectural finishes in Metro Vancouver.",`${SITE}/blog`,`<header class="hero"><div class="kicker">Stile di Leo · Journal</div><h1>Architectural Finishes & Design</h1><p>Practical guides and design insight for refined walls, fireplaces and surfaces across Metro Vancouver.</p></header><main class="wrap"><div class="grid">${cards||empty}</div>${pager}</main>`); }
async function postPage(slug:string){ const p=await opinly(`/post?slug=${encodeURIComponent(slug)}`); if(!p) return new Response(layout("Article not found | Stile di Leo","The requested article could not be found.",`${SITE}/blog/${esc(slug)}`,`<main class="error"><h1>Article not found</h1><a href="/blog">Return to the journal</a></main>`),{status:404,headers:{"content-type":"text/html; charset=utf-8"}}); const canonical=`${SITE}/blog/${p.slug}`; const hero=imageUrl(p.titleFile?.fileKey); const ld={"@context":"https://schema.org","@type":"BlogPosting",headline:p.title,description:p.metaDescription||p.description,datePublished:p.firstPublishedAt,dateModified:p.modifiedAt,mainEntityOfPage:canonical,url:canonical,image:hero||undefined,author:p.author?{"@type":"Person",name:p.author.name}:undefined,publisher:{"@type":"Organization",name:"Stile di Leo",url:SITE}}; const crumbs={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:SITE},{"@type":"ListItem",position:2,name:"Journal",item:`${SITE}/blog`},{"@type":"ListItem",position:3,name:p.title,item:canonical}]}; const body=`<main class="wrap post"><div class="kicker">${esc(p.category?.name||"Journal")}</div><h1>${esc(p.title)}</h1><div class="meta">${esc(date(p.firstPublishedAt))}${p.author?.name?` · ${esc(p.author.name)}`:""}</div><p class="lead">${esc(p.description||"")}</p>${hero?`<figure><img style="width:100%;height:auto" src="${esc(hero)}" alt="${esc(p.titleFile?.altText||p.title)}"></figure>`:""}<article class="content">${renderNode(p.content)}</article></main>`; return new Response(layout(p.metaTitle||`${p.title} | Stile di Leo`,p.metaDescription||p.description||"",canonical,body,[ld,crumbs]),{headers:{"content-type":"text/html; charset=utf-8","cache-control":"public, max-age=0, s-maxage=300, stale-while-revalidate=86400"}}); }
export default async (req:Request) => { try { if(req.method!=="GET"&&req.method!=="HEAD") return new Response("Method not allowed",{status:405}); const u=new URL(req.url); const path=u.pathname.replace(/^\/blog\/?/,""); if(!path) return new Response(await indexPage(u),{headers:{"content-type":"text/html; charset=utf-8","cache-control":"public, max-age=0, s-maxage=300, stale-while-revalidate=86400"}}); return postPage(decodeURIComponent(path.split("/")[0])); } catch(e){ console.error(e); return new Response(layout("Journal temporarily unavailable | Stile di Leo","The journal is temporarily unavailable.",`${SITE}/blog`,`<main class="error"><h1>Journal temporarily unavailable</h1><p>Please try again shortly.</p></main>`),{status:502,headers:{"content-type":"text/html; charset=utf-8"}}); } };
export const config={path:"/blog/*"};